### ISSUE TITLE
UI-Plus 0.4 AsyncErr: Lua: Runtime error from mod

### ISSUE THREAD

**Issue by ml-dp** [bousket/unified_inventory_plus#21] opened 2022-07-06 00:42 UTC
Just UI & UI-P enabled, and I get this error. No conflicting mods present. 

Error: [https://cdn.discordapp.com/attachments/369123175583186964/994039132366057554/unknown.png](url)

**Comment by fluxionary** [comment] 2023-02-26 18:06
(just pasting the image in the above link, no comment)
![image](https://user-images.githubusercontent.com/25628292/221428204-f28ce237-5661-43d9-90ff-171ab2427618.png)

**Comment by BuckarooBanzay** [comment] 2023-05-13 13:10
@cafelinked is this still an issue with the latest versions of UI and UI+? (works for me currently...)

**Comment by Niklp09** [comment] 2023-06-22 20:19
Cannot reproduce, closing.

**Closed as not planned by Niklp09** 2023-06-22 20:19 UTC
Labels: bug, question
